title: Simple Scratch game controller with a Raspberry Pi
hero_image: images/banner.png
description: Control a Scratch sprite with a simple switch on your Raspberry Pi
version: 4
listed: false
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Introduction
  - title: A simple switch
  - title: Keys vs switches
  - title: Adding a switch to a game
  
