title: simple-scratch-game-controller
hero_image: images/banner.png
description: simple-scratch-game-controller description
version: 4
listed: false
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
